# Generated by Django 3.2.5 on 2021-12-24 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wallpaper_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaperimage',
            name='wallpaper',
        ),
        migrations.AddField(
            model_name='wallpaperimage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AddField(
            model_name='wallpaperimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallpaperimage',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallpaperimage',
            name='sourceURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
