# Generated by Django 3.2.5 on 2021-12-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211224_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='category_bg/'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
