# Generated by Django 3.2.5 on 2021-12-24 18:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211224_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallpaperimage',
            options={'verbose_name': 'Wallpaper', 'verbose_name_plural': 'Wallpapers'},
        ),
        migrations.AlterField(
            model_name='category',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images/category_bg/'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None),
        ),
    ]
